name: ci
on: [push]
jobs:
  test:
    # use the reusable workflow to check out the code, install dependencies
    # and run the Cypress tests
    # https://github.com/bahmutov/cypress-workflows
    uses: cypress-io/github-action@v2
    with:
      start: 'yarn start'
      config-file: cypress.config.js
      # wait-on: "http://localhost:3000/"