name: ci
on: [push]
jobs:
  test:
    # use the reusable workflow to check out the code, install dependencies
    # and run the Cypress tests
    # https://github.com/bahmutov/cypress-workflows
    uses: bahmutov/cypress-workflows/.github/workflows/standard.yml@v1
    with:
      start: "yarn start"
      wait-on: "http://localhost:3000/"
      wait-on-timeout: 500 # seconds = 6 mins
      config-file: cypress.config.js